### PR TITLE
Added Image To PDF Conversion

### PR DESCRIPTION
**Pull request by TheSpeedX**
- [x] Added requirements.txt
- [x] Used Pythonic way to convert PPT to PDF
- [x] Added Image to PDF with PIL
- [x] Formatted code as per PEP8 standards

### CODE REVIEW

**Comment by TheSpeedX** [comment]
Fixes #4

**Comment by suraj-singh12** [comment]
@TheSpeedX , it is beautiful the way you refactored the code.

But there is an _error_ in the refactored code (your first commit), it broke the functionality of the tool to work with excel (```.xlsx```) files.

Also do check the 2nd commit where you used Pythonic way to convert PPT to PDF, probably you have missed something there. It is broken too.

```
Enter the file name(with extension): files/myppt.pptx
Traceback (most recent call last):
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 108, in <module>
    main()
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 98, in main
    Ppt2Pdf(filename)
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 49, in Ppt2Pdf
    ppt_processor.convert(filename, output_filename)
  File "C:\Users\suraj\AppData\Local\Programs\Python\Python39\lib\site-packages\ppt2pdf\main.py", line 22, in convert
    slides = powerpoint.Presentations.Open(inputFilePath)
_ctypes.COMError: (-2147024893, 'The system cannot find the path specified.', (None, None, None, 0, None))



Enter the file name(with extension): myexcel.xlsx
Traceback (most recent call last):
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 108, in <module>
    main()
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 102, in main
    Excel2Pdf(filename)
  File "C:\Users\suraj\Desktop\new_repo\main.py", line 58, in Excel2Pdf
    work_sheets = sheets.Worksheets[0]
AttributeError: 'NoneType' object has no attribute 'Worksheets'
```

Consider resolving these issues, then test on the sample files and make the PR.
- [ ] Above two issues resolved
- [ ] Tested the tool on sample files

**Comment by TheSpeedX** [comment]
Fixed PPT.
Excel is working fine, make sure you test on correct path.
image

**Comment by suraj-singh12** [comment]
Yes, it's working well.

**Pull request merged**
