### PR TITLE
implemented package dependency using poetry

### PR DESCRIPTION
**Pull request by glitchdawg**
tried to resolve some part of #15 by implementing dependency management using poetry.
Now provided that the user has installed [poetry](https://python-poetry.org/).
All the dependencies can be installed by a single command `poetry install`.

Proper documentation(changing the readme file) and resolving the linux api calls will be dealt with in later pushes. please create separate issue for these

### CODE REVIEW

**Comment by suraj-singh12** [comment]
Feel free to raise an issue.
I shall review it.

**Comment by suraj-singh12** [comment]
Is there not a command line way of installing `poetry` silently in the system after getting user permission?
That would suit better.

**Comment by glitchdawg** [comment]
> Is there not a command line way of installing `poetry` silently in the system after getting user permission? That would suit better.

I think what you are asking for is packaging this python application for distribution, so that user doesnt have to deal with  navigating to this directory and installing all the dependency . We have only implemented dependency management in this push.

There are several ways to package the app. We need to look for a way that suits our need. We could use RPM, create a pip installable package or use third party  bundling solutions like pyInstaller, py2exe,Nuitika etc. we could also just create an embeddable package in windows.

I will create a new issue after this push, creating a separate branch to deal with packaging issues would be ideal

**Comment by suraj-singh12** [comment]
Merging it into branch /poetry
Kindly rename your `master` to `poetry` using the command
`git branch -M poetry`
make a push again and reflect the same in this PR so I can merge!

**Comment by glitchdawg** [comment]
> Merging it into branch /poetry
> Kindly rename your `master` to `poetry` using the command
> `git branch -m poetry`
> make a push again and reflect the same in this PR so I can merge!

Will start on it shortly

**Pull request closed without merging**
