### PR TITLE
Add GUI using pyQt5

### PR DESCRIPTION
**Pull request by arijitparia2002**

### CODE REVIEW

**Comment by suraj-singh12** [comment]
Linked #7

**Comment by suraj-singh12** [comment]
Kindly add some screenshot of the UI

**Comment by arijitparia2002** [comment]
Screenshot (275)

**Comment by suraj-singh12** [comment]
Although it's not a replication of original UI, but I see this as a potential re-draw that might give rise to a completely new UI.
Good work man!

**Comment by arijitparia2002** [comment]
Thank you! I'll be adding the functions and also icon for this application soon.

**Comment by suraj-singh12** [comment]
Also shift from `enhancement` to `qt` branch.

**Comment by suraj-singh12** [comment]
closed with #17

**Pull request closed without merging**
